import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AppProvider } from "@/AppContext";
import Footer from "@/components/home/Footer";

const font = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AppProvider>
      <html lang="en">
        <body className={`${font.className}  lg:px-[60px] px-5`}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </AppProvider>
  );
}
